name: Dependabot
updates:
  - directory: /
    open-pull-requests-limit: 1
    package-ecosystem: gradle
    schedule:
      interval: daily
    labels:
      - "dependabot"
      - "dependencies"
version: 2